ruby '2.5.0'
source 'https://rubygems.org'

gem 'figaro'
gem 'pg'
gem 'puma'
gem 'rack-cors'
gem 'rails'

gem 'rest-client'

gem 'aws-sdk-s3'
gem 'shrine'

gem 'mini_magick'

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails'
end

group :development do
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
  gem 'web-console'
end
