ruby '2.5.0'
source 'https://rubygems.org'

gem 'figaro'
gem 'pg'
gem 'puma'
gem 'rack-cors'
gem 'rails'

gem 'aws-sdk-s3'
gem 'shrine'

group :development, :test do
  gem 'byebug'
  gem 'web-console'
end

group :development do
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
end
